2022-05-01 17:22:01 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-01 17:22:01 ERROR [main] (UserController.java:46) - Exception: User zane, does not exist
2022-05-01 17:22:01 INFO  [main] (UserController.java:37) - Info: try to find user by id: 1
2022-05-01 17:22:01 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-01 17:22:01 INFO  [main] (UserController.java:49) - Success: User: zane found!
2022-05-01 17:22:01 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-01 17:22:01 ERROR [main] (UserController.java:64) - Exception: User was not created, because password is bigger than 7 characters or password does not match
2022-05-01 17:22:01 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-01 17:22:01 INFO  [main] (UserController.java:71) - Success: User username, been created!
2022-05-01 17:22:01 INFO  [main] (CartController.java:65) - Info: try to remove item id: 1 from user: not_found
2022-05-01 17:22:01 ERROR [main] (CartController.java:68) - Exception: User not_found, does not exist!
2022-05-01 17:22:01 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: not_found
2022-05-01 17:22:01 ERROR [main] (CartController.java:45) - Exception: User not_found, does not exist!
2022-05-01 17:22:01 INFO  [main] (CartController.java:65) - Info: try to remove item id: 1 from user: zane
2022-05-01 17:22:01 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-01 17:22:01 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-01 17:22:01 ERROR [main] (OrderController.java:38) - Exception: User zane, does not exist!
2022-05-01 17:22:01 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-01 17:22:01 ERROR [main] (OrderController.java:52) - Exception: User zane, does not exist!
2022-05-01 17:22:01 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-01 17:22:01 INFO  [main] (OrderController.java:55) - Success: The order of user: zane found!
2022-05-01 17:22:01 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-01 17:22:01 INFO  [main] (OrderController.java:43) - Success: OrderId: null has been created by user: zane
2022-05-01 23:56:02 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-01 23:56:02 ERROR [main] (UserController.java:46) - Exception: User zane, does not exist
2022-05-01 23:56:02 INFO  [main] (UserController.java:37) - Info: try to find user by id: 1
2022-05-01 23:56:02 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-01 23:56:02 INFO  [main] (UserController.java:49) - Success: User: zane found!
2022-05-01 23:56:02 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-01 23:56:02 ERROR [main] (UserController.java:64) - Exception: User was not created, because password is bigger than 7 characters or password does not match
2022-05-01 23:56:02 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-01 23:56:02 INFO  [main] (UserController.java:71) - Success: User username, been created!
2022-05-01 23:56:02 INFO  [main] (CartController.java:65) - Info: try to remove item id: 1 from user: not_found
2022-05-01 23:56:02 ERROR [main] (CartController.java:68) - Exception: User not_found, does not exist!
2022-05-01 23:56:02 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: not_found
2022-05-01 23:56:02 ERROR [main] (CartController.java:45) - Exception: User not_found, does not exist!
2022-05-01 23:56:02 INFO  [main] (CartController.java:65) - Info: try to remove item id: 1 from user: zane
2022-05-01 23:56:02 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-01 23:56:02 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-01 23:56:02 ERROR [main] (OrderController.java:38) - Exception: User zane, does not exist!
2022-05-01 23:56:02 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-01 23:56:02 ERROR [main] (OrderController.java:52) - Exception: User zane, does not exist!
2022-05-01 23:56:02 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-01 23:56:02 INFO  [main] (OrderController.java:55) - Success: The order of user: zane found!
2022-05-01 23:56:02 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-01 23:56:02 INFO  [main] (OrderController.java:43) - Success: OrderId: null has been created by user: zane
2022-05-04 11:49:07 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:49:26 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:49:55 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:52:39 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:52:39 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart.
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 11:53:06 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:53:06 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart. {}
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 11:53:28 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:53:28 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart. Cart Repository error!
2022-05-04 11:56:33 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:56:33 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart. {}
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 11:57:13 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 11:57:13 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart.
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 12:05:44 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 12:05:44 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart.
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 23:05:59 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 23:05:59 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart.
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
2022-05-04 23:10:41 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-04 23:10:41 ERROR [main] (UserController.java:46) - Exception: User zane, does not exist
2022-05-04 23:10:41 INFO  [main] (UserController.java:37) - Info: try to find user by id: 1
2022-05-04 23:10:41 INFO  [main] (UserController.java:43) - Info: try to find user by name: zane
2022-05-04 23:10:41 INFO  [main] (UserController.java:49) - Success: User: zane found!
2022-05-04 23:10:41 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-04 23:10:41 ERROR [main] (UserController.java:64) - Exception: User was not created, because password is bigger than 7 characters or password does not match
2022-05-04 23:10:41 INFO  [main] (UserController.java:57) - Info: try to create user: username
2022-05-04 23:10:41 INFO  [main] (UserController.java:71) - Success: User username, been created!
2022-05-04 23:10:41 INFO  [main] (CartController.java:71) - Info: try to remove item id: 1 from user: not_found
2022-05-04 23:10:41 ERROR [main] (CartController.java:74) - Exception: User not_found, does not exist!
2022-05-04 23:10:41 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: not_found
2022-05-04 23:10:41 ERROR [main] (CartController.java:45) - Exception: User not_found, does not exist!
2022-05-04 23:10:41 INFO  [main] (CartController.java:71) - Info: try to remove item id: 1 from user: zane
2022-05-04 23:10:41 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 23:10:41 ERROR [main] (CartController.java:60) - [addToCart] Error occurred while save cart.
java.lang.RuntimeException: Cart Repository error!
	at com.example.demo.controllers.CartController.addToCart(CartController.java:58)
	at com.example.demo.controllers.CartControllerTest.testAddToCart_failed(CartControllerTest.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
2022-05-04 23:10:41 INFO  [main] (CartController.java:42) - Info: try to add item id: 1 to user: zane
2022-05-04 23:10:41 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-04 23:10:41 ERROR [main] (OrderController.java:38) - Exception: User zane, does not exist!
2022-05-04 23:10:41 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-04 23:10:41 ERROR [main] (OrderController.java:52) - Exception: User zane, does not exist!
2022-05-04 23:10:41 INFO  [main] (OrderController.java:50) - Info: try to get order for user: zane
2022-05-04 23:10:41 INFO  [main] (OrderController.java:55) - Success: The order of user: zane found!
2022-05-04 23:10:41 INFO  [main] (OrderController.java:36) - Info: try to find user by name: zane
2022-05-04 23:10:41 INFO  [main] (OrderController.java:43) - Success: OrderId: null has been created by user: zane
